// Generic constants
export const GITHUB_PROFILE_URL = "https://github.com/Aditya7799"
export const LINKEDIN_PROFILE_URL = "https://linkedin.com/aditya-dalvi"
export const INSTAGRAM_PROFILE_URL = "https://linkedin.com/aditya-dalvi"
export const FIRST_NAME = "Aditya"
export const LAST_NAME = "Dalvi"

// Home Page Related Constants
export const HOME_INTRO = "Hi There!"
export const HOME_INTRODUCTION_1 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pellentesque habitant morbi tristique senectus et netus. Tristique magna sit amet purus. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Posuere sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. Enim ut tellus elementum sagittis vitae et leo. Malesuada fames ac turpis egestas integer eget aliquet nibh praesent. Purus faucibus ornare suspendisse sed nisi lacus sed viverra tellus. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Feugiat scelerisque varius morbi enim nunc faucibus a. Enim neque volutpat ac tincidunt vitae semper. Purus faucibus ornare suspendisse sed nisi lacus sed viverra. Consequat interdum varius sit amet. Faucibus purus in massa tempor nec feugiat nisl pretium. Fermentum et sollicitudin ac orci phasellus egestas tellus."
export const HOME_INTRODUCTION_2 = "Adipiscing elit duis tristique sollicitudin nibh. Nullam ac tortor vitae purus faucibus ornare suspendisse sed. Interdum varius sit amet mattis vulputate enim nulla aliquet porttitor. Leo duis ut diam quam nulla. Duis tristique sollicitudin nibh sit amet commodo nulla facilisi nullam. Lacus luctus accumsan tortor posuere ac. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Quam vulputate dignissim suspendisse in est. Viverra suspendisse potenti nullam ac tortor vitae purus faucibus. Ac orci phasellus egestas tellus rutrum tellus pellentesque eu. Nunc consequat interdum varius sit amet. Nulla porttitor massa id neque aliquam vestibulum. Dolor sed viverra ipsum nunc aliquet bibendum. At volutpat diam ut venenatis tellus in metus vulputate. Tellus elementum sagittis vitae et. Et egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Urna duis convallis convallis tellus id interdum velit. Sit amet tellus cras adipiscing enim eu turpis. Blandit libero volutpat sed cras ornare arcu dui vivamus."

